version: '3'

services: 
  
    nodeapp:
      build:
        context: nodeapp
        dockerfile: Dockerfile.prod        
      container_name: nodeapp
      restart: always      
      entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
      networks: 
        - nodeappnet
      tty: true        
      ports:
        - 3000:3000
      depends_on:
        - db
    
    nginx:
      build:
        context: nginx
        dockerfile: Dockerfile.prod
      container_name: nginx
      restart: always
      networks:
        - nodeappnet
      tty: true
      ports:
        - 8080:8080
      depends_on: 
        - nodeapp
      
    db:
      image: mysql:5.7
      command: --innodb-use-native-aio=0
      container_name: db
      restart: always
      volumes:
        - /tmp/mysql:/var/lib/mysql
      ports:
        - 3306:3306
      environment: 
        - MYSQL_DATABASE=nodedb
        - MYSQL_ROOT_PASSWORD=MYSQL_ROOT_PASSWORD
        - MYSQL_USER=root
      networks: 
          - nodeappnet

networks: 
  nodeappnet:
    driver: bridge
