version: '3'

services: 
  
    nodeapp:
      build:
        context: ./nodeapp
        dockerfile: Dockerfile.prod
      container_name: nodeapp
      networks: 
        - nodeappnet
      tty: true        
      ports:
        - "3000:3000"
      depends_on:
        - db
        - nginx
    
    nginx:
      build:
        context: ./nginx
        dockerfile: Dockerfile.prod
      restart: always
      networks: 
        - nodeappnet
      tty: true
      ports:
        - "8080:8080"
      
    db:
      image: mysql:5.7
      command: --innodb-use-native-aio=0
      container_name: nodeappdb
      restart: always
      tty: true
      volumes: 
        - /tmp/mysql:/var/lib/mysql
        - ./mysql/setup.sql:/tmp/setup.sql
        - ./mysql/rundb.sh:/docker-entrypoint-initdb.d/rundb.sh
      environment: 
        - MYSQL_DATABASE=nodedb
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USER=root
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      networks: 
          - nodeappnet

networks: 
  nodeappnet:
    driver: bridge
